site_name: "Pymaxflight"
repo_url: "https://github.com/Clarkson-IMPETUS/pyMaxFlight"
site_dir: "site"
docs_dir: "docs"

theme:
  name: material
  icon:
    logo: material/file-check-outline
  include_sidebar: true
  palette:
    - scheme: slate
      primary: red
      accent: red
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
